### PR TITLE
Added support for the SLPI DSP

### PR DESCRIPTION
**Pull request by mcharleb**

### CODE REVIEW

**Comment by julianoes** [comment]
@mcharleb I found a problem since this PR. I see that you moved all the custom definition which were needed to qurt_flags.cmake. However, this new file is not included anywhere as far as I can tell. With the Firmware repo pointing to the latest cmake_hexagon, it therefore doesn't compile anymore.

Did you just forget to include it? Or do we need to include it in Firmware/DriverFramework separately?

**Comment by mcharleb** [comment]
You need to include it separately, and the Toolchain file should not be re-included as it currently is. The flags don't persist when passed from the cmake invocation. The toolchain file is included again in the CMakeLists.txt in Firmware which IMO is just wrong. It also forces that pattern on all other projects using cmake_hexagon

**Comment by julianoes** [comment]
Ok thanks, I didn't know that. I'll try to change it. Can you point me to the file/line where the qurt_flags.cmake should be included?

**Comment by julianoes** [comment]
I can see that the toolchain file is included in https://github.com/PX4/Firmware/blob/master/cmake/configs/qurt_sdflight_default.cmake#L13 but I can't see it getting included in any CMakeLists.txt.

**Comment by julianoes** [comment]
@mcharleb: I tried to get it to compile again after these changes and I had some troubles but finally managed somehow. I'm pretty confused about how all the cmake stuff should work, so I'd value your input or fixing here: https://github.com/PX4/Firmware/pull/5552.

It does build on my local machine but not on semaphoreci yet, I need to check what's going on inside docker.

**Pull request merged**
